spring.application.name=reactiveprogramming

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/reactive
spring.datasource.username=postgres
spring.datasource.password=Shakti
# spring.datasource.password=ishan!1
# spring.datasource.password=Sulav_1552
# spring.datasource.password=rijan1234
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
 
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration

# jwt.secretKey=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

# swagger
# Enable OpenAPI Documentation
# springdoc.api-docs.enabled=true
# springdoc.api-docs.path=/v3/api-docs
# springdoc.swagger-ui.enabled=true
# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.paths-to-match=/**
# springdoc.swagger-ui.operationsSorter=method

